name: dev
services:
  # Include Nginx
  nginx:
    extends:
      file: docker/nginx.yml
      service: nginx

  # Include MySQL databases
  mysql-user:
    extends:
      file: docker/databases.yml
      service: mysql-user

  mysql-msreels:
    extends:
      file: docker/databases.yml
      service: mysql-msreels
  mysql-likeComment:
    extends:
      file: docker/databases.yml
      service: mysql-likeComment            
  mysql-notification:
    extends:
      file: docker/databases.yml
      service: mysql-notification
  # Include API Gateway
  apigateway:
    extends:
      file: docker/apigateway.yml
      service: apigateway

  # Include MsReels service
  msreels:
    extends:
      file: docker/msreels.yml
      service: msreels
