name: remote-apigateway
services:
  remote-apigateway:
    image: shegga/apigateway
    ports:
      - "8081:8080"
    environment:
      - JHIPSTER_APP_NAME=RemoteApiGateway
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,api-docs
      # Connect to Consul through Nginx proxy
      - SPRING_CLOUD_CONSUL_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul.appf4.io.vn
      - SPRING_CLOUD_CONSUL_PORT=443
      - SPRING_CLOUD_CONSUL_SCHEME=https
      # Disable discovery and config temporarily to isolate the issue
      - SPRING_CLOUD_CONSUL_DISCOVERY_ENABLED=true
      - SPRING_CLOUD_CONSUL_CONFIG_ENABLED=true
      - SPRING_CLOUD_SERVICE_REGISTRY_AUTO_REGISTRATION_ENABLED=true
      - SPRING_CLOUD_CONSUL_DISCOVERY_SERVICE_NAME=remote-apigateway
      - SPRING_CLOUD_CONSUL_DISCOVERY_PREFER_IP_ADDRESS=true
      - SPRING_CLOUD_CONSUL_DISCOVERY_IP_ADDRESS=appf4.io.vn
      - SPRING_CLOUD_CONSUL_DISCOVERY_PORT=8083
      # Add Authorization header with Bearer token (Replace <TOKEN> manually)
      - SPRING_CLOUD_CONSUL_CONFIG_HEADERS_Authorization=Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI4TEgyYXBXZ0RPRHM3YkFIVmpuX3BsaVc5cU9VNDBBQ3F6RWM2d1RReWZvIn0.eyJleHAiOjE3NDM3NzgzMTksImlhdCI6MTc0Mzc3ODAxOSwianRpIjoiM2FhN2YxN2QtYzFiZC00NjI1LWI1NzEtOTllZmRlZjQ5OTZmIiwiaXNzIjoiaHR0cHM6Ly9rZXljbG9hay5hcHBmNC5pby52bi9yZWFsbXMvamhpcHN0ZXIiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiNGM5NzM4OTYtNTc2MS00MWZjLTgyMTctMDdjNWQxM2EwMDRiIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoid2ViX2FwcCIsInNpZCI6IjE4MDI4ZDUwLWIzNjEtNGQzYi04OTYxLWRiMjUyZmI5NDM0MSIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cDovLzEyNy4wLjAuMTo4NzYxIiwiaHR0cHM6Ly9hcHBmNC5pby52bi8qIiwiaHR0cDovL2xvY2FsaG9zdDo4MDgwIiwiaHR0cHM6Ly9jb25zdWwuYXBwZjQuaW8udm4vKiIsImh0dHBzOi8vbXlzcWwuYXBwZjQuaW8udm4vKiIsImh0dHBzOi8va2Fma2EuYXBwZjQuaW8udm4vKiIsImh0dHBzOi8vcmVkaXMuYXBwZjQuaW8udm4vKiIsImh0dHA6Ly9sb2NhbGhvc3Q6ODEwMCIsImh0dHBzOi8va2FmZHJvcC5hcHBmNC5pby52bi8qIiwiaHR0cHM6Ly9sb2NhbGhvc3Q6ODA4MCJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiUk9MRV9VU0VSIiwib2ZmbGluZV9hY2Nlc3MiLCJST0xFX0FETUlOIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInJvbGVzIjpbIlJPTEVfVVNFUiIsIm9mZmxpbmVfYWNjZXNzIiwiUk9MRV9BRE1JTiIsInVtYV9hdXRob3JpemF0aW9uIl0sIm5hbWUiOiJBZG1pbiBBZG1pbmlzdHJhdG9yIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiYWRtaW4iLCJnaXZlbl9uYW1lIjoiQWRtaW4iLCJmYW1pbHlfbmFtZSI6IkFkbWluaXN0cmF0b3IiLCJlbWFpbCI6ImFkbWluQGxvY2FsaG9zdCJ9.Ch4c_lVD5OnUHO3AbekAcLFyN9VxLchNwiSNlgI7hb6aHf49kETdhZcvEabO3n5Ipm2YQnTVKF5Ef-2gQcR_n6X44Li88ksd7ErKdu1qU9qqqBrBWvHvZigO9kFqW0lwo_tW7HebDe0pAt2DP51gP87GuyLRrrjvDuPxhz3yNziW8N0_jWjYaYrllIAQCP1AKe8eQ-mdimPFlBWHHXEIKe-0ldGZ2tLr6_RYZPZL767vtcsJNngsc5aC90aDlnThPWCQUauc92cbQXqR3PqeV3RYQa0HjBsmg8vtaBHFiOUJUiZqkELUxOZ5UrsvMiqxeTboxkIpFLhwf5rneuzPAg
      - SPRING_CLOUD_CONSUL_ACL_TOKEN=${CONSUL_HTTP_TOKEN:-}
      - SPRING_CLOUD_CONSUL_CONFIG_ACL_TOKEN=${CONSUL_HTTP_TOKEN:-}
      - SPRING_CLOUD_CONSUL_DISCOVERY_ACL_TOKEN=${CONSUL_HTTP_TOKEN:-}
      # Skip TLS certificate validation
      - SPRING_CLOUD_CONSUL_TLS_SKIP_VERIFY=true
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=https://keycloak.appf4.io.vn/realms/jhipster
      - JHIPSTER_SECURITY_OAUTH2_AUTH_SERVER_URL=https://keycloak.appf4.io.vn
      - SPRING_R2DBC_URL=r2dbc:mysql://appf4.io.vn:3306/apigateway
      - SPRING_LIQUIBASE_URL=jdbc:mysql://appf4.io.vn:3306/apigateway?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_CACHE_REDIS_SERVER=redis://appf4.io.vn:6379
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=appf4.io.vn:9092
      - SPRING_KAFKA_SECURITY_PROTOCOL=SSL
      - SPRING_KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=""
      - SPRING_KAFKA_PROPERTIES_SSL_TRUSTSTORE_LOCATION=/app/config/kafka.truststore.jks
      - SPRING_KAFKA_PROPERTIES_SSL_TRUSTSTORE_PASSWORD=f4security
      - SPRING_KAFKA_PROPERTIES_SSL_KEYSTORE_LOCATION=/app/config/kafka.keystore.jks
      - SPRING_KAFKA_PROPERTIES_SSL_KEYSTORE_PASSWORD=f4security
      - SPRING_KAFKA_PROPERTIES_SSL_KEY_PASSWORD=f4security
    volumes:
      - ./kafka/ssl/kafka.truststore.jks:/app/config/kafka.truststore.jks
      - ./kafka/ssl/kafka.keystore.jks:/app/config/kafka.keystore.jks

  msmedia:
    image: tuongtran1345/msmedia
    ports:
      - "8084:8081"
    environment:
      - JHIPSTER_APP_NAME=MsMediaApp
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,api-docs
      # Connect to Consul through Nginx proxy
      - SPRING_CLOUD_CONSUL_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul.appf4.io.vn
      - SPRING_CLOUD_CONSUL_PORT=443
      - SPRING_CLOUD_CONSUL_SCHEME=https
      # Disable discovery and config temporarily to isolate the issue
      - SPRING_CLOUD_CONSUL_DISCOVERY_ENABLED=true
      - SPRING_CLOUD_CONSUL_CONFIG_ENABLED=true
      - SPRING_CLOUD_SERVICE_REGISTRY_AUTO_REGISTRATION_ENABLED=true
      - SPRING_CLOUD_CONSUL_DISCOVERY_SERVICE_NAME=remote-msmedia
      - SPRING_CLOUD_CONSUL_DISCOVERY_PREFER_IP_ADDRESS=true
      - SPRING_CLOUD_CONSUL_DISCOVERY_IP_ADDRESS=appf4.io.vn
      - SPRING_CLOUD_CONSUL_DISCOVERY_PORT=8084
      # Add Authorization header with Bearer token (Replace <TOKEN> manually)
      - SPRING_CLOUD_CONSUL_CONFIG_HEADERS_Authorization=Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI4TEgyYXBXZ0RPRHM3YkFIVmpuX3BsaVc5cU9VNDBBQ3F6RWM2d1RReWZvIn0.eyJleHAiOjE3NDM3NzgzMTksImlhdCI6MTc0Mzc3ODAxOSwianRpIjoiM2FhN2YxN2QtYzFiZC00NjI1LWI1NzEtOTllZmRlZjQ5OTZmIiwiaXNzIjoiaHR0cHM6Ly9rZXljbG9hay5hcHBmNC5pby52bi9yZWFsbXMvamhpcHN0ZXIiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiNGM5NzM4OTYtNTc2MS00MWZjLTgyMTctMDdjNWQxM2EwMDRiIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoid2ViX2FwcCIsInNpZCI6IjE4MDI4ZDUwLWIzNjEtNGQzYi04OTYxLWRiMjUyZmI5NDM0MSIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cDovLzEyNy4wLjAuMTo4NzYxIiwiaHR0cHM6Ly9hcHBmNC5pby52bi8qIiwiaHR0cDovL2xvY2FsaG9zdDo4MDgwIiwiaHR0cHM6Ly9jb25zdWwuYXBwZjQuaW8udm4vKiIsImh0dHBzOi8vbXlzcWwuYXBwZjQuaW8udm4vKiIsImh0dHBzOi8va2Fma2EuYXBwZjQuaW8udm4vKiIsImh0dHBzOi8vcmVkaXMuYXBwZjQuaW8udm4vKiIsImh0dHA6Ly9sb2NhbGhvc3Q6ODEwMCIsImh0dHBzOi8va2FmZHJvcC5hcHBmNC5pby52bi8qIiwiaHR0cHM6Ly9sb2NhbGhvc3Q6ODA4MCJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiUk9MRV9VU0VSIiwib2ZmbGluZV9hY2Nlc3MiLCJST0xFX0FETUlOIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInJvbGVzIjpbIlJPTEVfVVNFUiIsIm9mZmxpbmVfYWNjZXNzIiwiUk9MRV9BRE1JTiIsInVtYV9hdXRob3JpemF0aW9uIl0sIm5hbWUiOiJBZG1pbiBBZG1pbmlzdHJhdG9yIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiYWRtaW4iLCJnaXZlbl9uYW1lIjoiQWRtaW4iLCJmYW1pbHlfbmFtZSI6IkFkbWluaXN0cmF0b3IiLCJlbWFpbCI6ImFkbWluQGxvY2FsaG9zdCJ9.Ch4c_lVD5OnUHO3AbekAcLFyN9VxLchNwiSNlgI7hb6aHf49kETdhZcvEabO3n5Ipm2YQnTVKF5Ef-2gQcR_n6X44Li88ksd7ErKdu1qU9qqqBrBWvHvZigO9kFqW0lwo_tW7HebDe0pAt2DP51gP87GuyLRrrjvDuPxhz3yNziW8N0_jWjYaYrllIAQCP1AKe8eQ-mdimPFlBWHHXEIKe-0ldGZ2tLr6_RYZPZL767vtcsJNngsc5aC90aDlnThPWCQUauc92cbQXqR3PqeV3RYQa0HjBsmg8vtaBHFiOUJUiZqkELUxOZ5UrsvMiqxeTboxkIpFLhwf5rneuzPAg
      - SPRING_CLOUD_CONSUL_ACL_TOKEN=${CONSUL_HTTP_TOKEN:-}
      - SPRING_CLOUD_CONSUL_CONFIG_ACL_TOKEN=${CONSUL_HTTP_TOKEN:-}
      - SPRING_CLOUD_CONSUL_DISCOVERY_ACL_TOKEN=${CONSUL_HTTP_TOKEN:-}
      # Skip TLS certificate validation
      - SPRING_CLOUD_CONSUL_TLS_SKIP_VERIFY=true
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=https://keycloak.appf4.io.vn/realms/jhipster
      - JHIPSTER_SECURITY_OAUTH2_AUTH_SERVER_URL=https://keycloak.appf4.io.vn
      - SPRING_DATASOURCE_URL=jdbc:mysql://appf4.io.vn:3306/msmedia?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - SPRING_LIQUIBASE_URL=jdbc:mysql://appf4.io.vn:3306/msmedia?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_CACHE_REDIS_SERVER=redis://appf4.io.vn:6379
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=appf4.io.vn:9092
      - SPRING_KAFKA_SECURITY_PROTOCOL=SSL
      - SPRING_KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=""
      - SPRING_KAFKA_PROPERTIES_SSL_TRUSTSTORE_LOCATION=/app/config/kafka.truststore.jks
      - SPRING_KAFKA_PROPERTIES_SSL_TRUSTSTORE_PASSWORD=f4security
      - SPRING_KAFKA_PROPERTIES_SSL_KEYSTORE_LOCATION=/app/config/kafka.keystore.jks
      - SPRING_KAFKA_PROPERTIES_SSL_KEYSTORE_PASSWORD=f4security
      - SPRING_KAFKA_PROPERTIES_SSL_KEY_PASSWORD=f4security
    volumes:
      - ./kafka/ssl/kafka.truststore.jks:/app/config/kafka.truststore.jks
      - ./kafka/ssl/kafka.keystore.jks:/app/config/kafka.keystore.jks