name: jenkins
networks:
  f4_network:
      external: true
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-lite
    user: "root"  # Run as Jenkins user to match folder permissions
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /root/docker-compose/docker-compose:/var/jenkins_home/project  # Corrected mount
      - /var/run/docker.sock:/var/run/docker.sock  # Allow Jenkins to control Docker
      - /usr/bin/docker:/usr/bin/docker            # Provides the Docker CLI
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - f4_network

volumes:
  jenkins_home:
