name: dev
services:
  # Include MySQL databases

  mysql-msmedia:
    extends:
      file: docker/databases.yml
      service: mysql-msmedia

  mysql-msreels:
    extends:
      file: docker/databases.yml
      service: mysql-msreels

  # Include API Gateway
  apigateway:
    extends:
      file: docker/apigateway.yml
      service: apigateway

  # Include MsMedia service
  msmedia:
    extends:
      file: docker/msmedia.yml
      service: msmedia

  # Include MsReels service
  msreels:
    extends:
      file: docker/msreels.yml
      service: msreels

  # Include Nginx
  nginx:
    extends:
      file: docker/nginx.yml
      service: nginx
