name: dev
services:
  # Include Nginx
  nginx:
    extends:
      file: docker/nginx.yml
      service: nginx
  # Include MySQL databases
  mysql-user:
    extends:
      file: docker/databases.yml
      service: mysql-user
  mysql-msreels:
    extends:
      file: docker/databases.yml
      service: mysql-msreels
  mysql-commentlike:
    extends:
      file: docker/databases.yml
      service: mysql-commentlike
  mysql-notification:
    extends:
      file: docker/databases.yml
      service: mysql-notification
  mysql-feed:
    extends:
      file: docker/databases.yml
      service: mysql-feed
  # Include API Gateway
  apigateway:
    extends:
      file: docker/apigateway.yml
      service: apigateway
  # Include MsReels service
  msreels:
    extends:
      file: docker/msreels.yml
      service: msreels
  msuser:
    extends:
      file: docker/msuser.yml
      service: msuser
  mscommentlike:
    extends:
      file: docker/mscommentlike.yml
      service: mscommentlike
  msnotification:
    extends:
      file: docker/msnotification.yml
      service: msnotification
  msfeed:
    extends:
      file: docker/msfeed.yml
      service: msfeed
