name: dev
services:
  # Include Nginx
  nginx:
    extends:
      file: docker/nginx.yml
      service: nginx
  # Include MySQL databases
  mysql-user:
    extends:
      file: docker/databases.yml
      service: mysql-user
  mysql-msreel:
    extends:
      file: docker/databases.yml
      service: mysql-msreel
  mysql-commentlike:
    extends:
      file: docker/databases.yml
      service: mysql-commentlike
  mysql-notification:
    extends:
      file: docker/databases.yml
      service: mysql-notification
  mysql-feed:
    extends:
      file: docker/databases.yml
      service: mysql-feed
  # Include API Gateway
  msgateway:
    extends:
      file: docker/apigateway.yml
      service: apigateway
  # Include msreel service
  msreel:
    extends:
      file: docker/msreel.yml
      service: msreel
  msuser:
    extends:
      file: docker/msuser.yml
      service: msuser
  mscommentlike:
    extends:
      file: docker/mscommentlike.yml
      service: mscommentlike
  msnotification:
    extends:
      file: docker/msnotification.yml
      service: msnotification
  msfeed:
    extends:
      file: docker/msfeed.yml
      service: msfeed
