version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-lite
    user: "root"  # Run as Jenkins user to match folder permissions
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /root/docker-compose/docker-compose:/var/jenkins_home/project  # Corrected mount
      - /var/run/docker.sock:/var/run/docker.sock  # Allow Jenkins to control Docker
      - /usr/bin/docker:/usr/bin/docker            # Provides the Docker CLI
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
    deploy:
      resources:
        limits:
          memory: 1g
volumes:
  jenkins_home:
