name: dev
services:
  mysql-user:
    extends:
      file: ./mysql.yml
      service: mysql
    volumes:
      - ../src/data/mysql-user:/var/lib/mysql
    ports:
      - "3381:3306"
    environment:
      MYSQL_DATABASE: user
    command: --local-infile=1 --lower_case_table_names=1
    healthcheck:
      test: [ "CMD-SHELL", "mysql -e 'SHOW DATABASES;' && sleep 5" ]
      interval: 5s
      timeout: 10s
      retries: 10 
 
  mysql-msreels:
    extends:
      file: ./mysql.yml
      service: mysql
    volumes:
      - ../src/data/mysql-msreels:/var/lib/mysql
    ports:
      - "3382:3306"
    environment:
      MYSQL_DATABASE: msreels
    command: --local-infile=1 --lower_case_table_names=1
    healthcheck:
      test: [ "CMD-SHELL", "mysql -e 'SHOW DATABASES;' && sleep 5" ]
      interval: 5s
      timeout: 10s
      retries: 10 

  mysql-commentlike:
    extends:
      file: ./mysql.yml
      service: mysql
    volumes:
      - ../src/data/mysql-commentlike:/var/lib/mysql
    ports:
      - "3385:3306"
    environment:
      MYSQL_DATABASE: commentlike
    command: --local-infile=1 --lower_case_table_names=1
    healthcheck:
      test: [ "CMD-SHELL", "mysql -e 'SHOW DATABASES;' && sleep 5" ]
      interval: 5s
      timeout: 10s
      retries: 10 

  mysql-notification:
    extends:
      file: ./mysql.yml
      service: mysql
    volumes:
      - ../src/data/mysql-notification:/var/lib/mysql
    ports:
      - "3383:3306"
    environment:
      MYSQL_DATABASE: notification
    healthcheck:
      test: [ "CMD-SHELL", "mysql -e 'SHOW DATABASES;' && sleep 5" ]
      interval: 5s
      timeout: 10s
      retries: 10 

  mysql-feed:
    extends:
      file: ./mysql.yml
      service: mysql
    volumes:
      - ../src/data/mysql-feed:/var/lib/mysql
    ports:
      - "3384:3306"
    environment:
      MYSQL_DATABASE: feed
    command: --local-infile=1 --lower_case_table_names=1
    healthcheck:
      test: [ "CMD-SHELL", "mysql -e 'SHOW DATABASES;' && sleep 5" ]
      interval: 5s
      timeout: 10s
      retries: 10

