name: dev
services:

  mysql-msmedia:
    extends:
      file: ./mysql.yml
      service: mysql
    volumes:
      - ../src/data/mysql-msmedia:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: msmedia
    healthcheck:
      test: [ "CMD-SHELL", "mysql -e 'SHOW DATABASES;' && sleep 5" ]
      interval: 5s
      timeout: 10s
      retries: 10
  
  mysql-msreels:
    extends:
      file: ./mysql.yml
      service: mysql
    volumes:
      - ../src/data/mysql-msreels:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: msreels
    healthcheck:
      test: [ "CMD-SHELL", "mysql -e 'SHOW DATABASES;' && sleep 5" ]
      interval: 5s
      timeout: 10s
      retries: 10 