name: dev
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/conf.d:/etc/nginx/conf.d
      - ../nginx/letsencrypt:/etc/letsencrypt
      - ../nginx/www:/var/www/html
      - ../nginx/log:/var/log/nginx
    depends_on:
      apigateway:
        condition: service_started 